version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    networks:
      - medai-network

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000/query
    depends_on:
      - backend
    networks:
      - medai-network

networks:
  medai-network:
    driver: bridge
